
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kalendar_development
  username: kalendar
  password: rdenadark

test:
  <<: *default
  database: kalendar_test
  username: kalendar
  password: rdenadark

production:
  <<: *default
  database: kalendar_production
  username: kalendar
  password: rdenadark
